#!/usr/bin/env bash
set -euo pipefail

# Minimum Neovim version numb.nvim supports. Kept in sync with the version
# matrix in .github/workflows/ci.yml.
MIN_NVIM_VERSION="0.10"

# Every Lua directory that is part of the plugin, including the plugin/ shim, the
# headless test suite and the verification scripts, so formatting and lint cannot
# drift there.
LUA_PATHS=(lua plugin tests scripts)

# Every tracked file that states the supported Neovim version. Bumping the floor
# means editing all of them, and missing one is invisible until a user on the old
# version believes a promise nothing else keeps.
FLOOR_SITES=(
  lua/numb/health.lua
  scripts/check.sh
  tests/run.lua
  doc/numb.txt
  README.md
  CONTRIBUTING.md
  .github/workflows/ci.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
)

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

usage() {
  cat <<'EOF'
Usage: scripts/check.sh [stage ...]

Stages:
  format   stylua --check over the Lua sources
  lint     selene over the Lua sources
  docs     help file against the Lua sources, dashes, stated Neovim floor
  nvim     Neovim version floor, load smoke test, test suite, health check

With no arguments every stage runs. CI splits them so the tool-only stages run
once while the nvim stage runs across the Neovim version matrix.
EOF
}

run_format=1
run_lint=1
run_docs=1
run_nvim=1

if [ "$#" -gt 0 ]; then
  run_format=0
  run_lint=0
  run_docs=0
  run_nvim=0
  for stage in "$@"; do
    case "$stage" in
      format) run_format=1 ;;
      lint) run_lint=1 ;;
      docs) run_docs=1 ;;
      nvim) run_nvim=1 ;;
      -h | --help)
        usage
        exit 0
        ;;
      *)
        echo "Unknown stage: $stage" >&2
        usage >&2
        exit 2
        ;;
    esac
  done
fi

if [ "$run_format" -eq 1 ]; then
  echo "==> Formatting"
  if ! command -v stylua >/dev/null 2>&1; then
    echo "stylua not found. Install it (https://github.com/JohnnyMorganz/StyLua) to run formatting checks."
    exit 1
  fi
  stylua --check "${LUA_PATHS[@]}"
fi

if [ "$run_lint" -eq 1 ]; then
  echo "==> Lint"
  if ! command -v selene >/dev/null 2>&1; then
    echo "selene not found. Install it (https://github.com/Kampfkarren/selene) to run lint checks."
    exit 1
  fi
  selene "${LUA_PATHS[@]}"
fi

if [ "$run_docs" -eq 1 ]; then
  echo "==> Docs"
  if ! command -v nvim >/dev/null 2>&1; then
    echo "nvim not found. Install Neovim ${MIN_NVIM_VERSION}+ to run the doc checks."
    exit 1
  fi

  # doc/tags is generated by every plugin manager at install time, so a committed
  # copy can only go stale and conflict.
  if git ls-files --error-unmatch doc/tags >/dev/null 2>&1; then
    echo "doc/tags is tracked; it is generated by :helptags and must stay ignored." >&2
    exit 1
  fi

  nvim -l scripts/verify_doc.lua

  # Matched by code point, not by UTF-8 byte, so this file does not have to
  # contain the characters it rejects. A byte escape like \xe2 is read as the
  # single code point U+00E2 in a UTF-8 locale, which matches nothing here, so
  # the byte form silently passed everything. Every tracked file is covered, not
  # just the help file, because most of the prose lives elsewhere.
  if git ls-files -z | xargs -0 grep -lP '\x{2013}|\x{2014}'; then
    echo "The files above use an en dash or em dash; use a plain hyphen." >&2
    exit 1
  fi

  echo "==> Neovim floor is stated consistently"
  for site in "${FLOOR_SITES[@]}"; do
    if ! grep -q "${MIN_NVIM_VERSION}" "$site"; then
      echo "$site does not mention Neovim ${MIN_NVIM_VERSION}; the stated floor has drifted." >&2
      exit 1
    fi
  done
  echo "  ${#FLOOR_SITES[@]} files agree on ${MIN_NVIM_VERSION}"
fi

if [ "$run_nvim" -eq 1 ]; then
  echo "==> Neovim version"
  if ! command -v nvim >/dev/null 2>&1; then
    echo "nvim not found. Install Neovim ${MIN_NVIM_VERSION}+ to run the smoke test."
    exit 1
  fi
  # has() understands dev builds, so nightly is accepted while 0.9 and older are
  # rejected with a clear message instead of an obscure missing-API error later.
  if ! nvim --headless --clean \
    +"lua if vim.fn.has('nvim-${MIN_NVIM_VERSION}') == 1 then vim.cmd 'qall!' end" \
    +"cquit 1" >/dev/null 2>&1; then
    echo "Neovim $(nvim --version | sed -n '1s/^NVIM //p') is too old."
    echo "numb.nvim requires Neovim ${MIN_NVIM_VERSION} or newer."
    exit 1
  fi
  nvim --version | sed -n '1p'

  echo "==> Neovim smoke test"
  nvim -l scripts/verify_load.lua

  echo "==> Plugin tests"
  nvim --headless -u tests/init.lua -i NONE -n +"lua require('tests.run').run()" +qall

  # The suite stubs vim.health to make the reporting decisions testable, so only
  # this exercises the real API and the real :checkhealth dispatch.
  echo "==> Health check"
  nvim -l scripts/verify_health.lua
fi

echo "All checks passed."
